<a href="https://colab.research.google.com/github/mflazaro/bases_ds_python/blob/main/1_desafio_datasers.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

**Dataset_1**

In [ ]:
url_ds_1 = 'https://raw.githubusercontent.com/mflazaro/bases_ds_python/main/bankloans.csv'

df_st_1 = pd.read_csv(url_ds_1)

df_st_1

      age  ed  employ  address  income  debtinc   creddebt   othdebt  default
0      41   3      17       12     176      9.3  11.359392  5.008608      1.0
1      27   1      10        6      31     17.3   1.362202  4.000798      0.0
2      40   1      15       14      55      5.5   0.856075  2.168925      0.0
3      41   1      15       14     120      2.9   2.658720  0.821280      0.0
4      24   2       2        0      28     17.3   1.787436  3.056564      1.0
...   ...  ..     ...      ...     ...      ...        ...       ...      ...
1145   34   1      12       15      32      2.7   0.239328  0.624672      NaN
1146   32   2      12       11     116      5.7   4.026708  2.585292      NaN
1147   48   1      13       11      38     10.8   0.722304  3.381696      NaN
1148   35   2       1       11      24      7.8   0.417456  1.454544      NaN
1149   37   1      20       13      41     12.9   0.899130  4.389870      NaN

[1150 rows x 9 columns]

Caracteristicas del Dataset_1:

age: Age of the Customers /
ed: Education Level /
employ: Work Experience /
address: Address of the Customer /
income: Yearly Income of the customer /
debtinc: Debt to Income Ratio /
creddebt: Credit to Debt ratio /
othdebt: Other debts /
default: Customer defaulted in the past (1= defaulted, 0=Never defaulted)

**Dataset_2**

In [ ]:
url_ds_2 = 'https://raw.githubusercontent.com/mflazaro/bases_ds_python/main/credit_risk_dataset.csv'

df_st_2 = pd.read_csv(url_ds_2)

df_st_2

,person_age,person_income,person_home_ownership,person_emp_length,loan_intent,loan_grade,loan_amnt,loan_int_rate,loan_status,loan_percent_income,cb_person_default_on_file,cb_person_cred_hist_length
0,22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3
1,21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.10,N,2
2,25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3
3,23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2
4,24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4
...,...,...,...,...,...,...,...,...,...,...,...,...
32576,57,53000,MORTGAGE,1.0,PERSONAL,C,5800,13.16,0,0.11,N,30
32577,54,120000,MORTGAGE,4.0,PERSONAL,A,17625,7.49,0,0.15,N,19
32578,65,76000,RENT,3.0,HOMEIMPROVEMENT,B,35000,10.99,1,0.46,N,28
32579,56,150000,MORTGAGE,5.0,PERSONAL,B,15000,11.48,0,0.10,N,26
32580,66,42000,RENT,2.0,MEDICAL,B,6475,9.99,0,0.15,N,30

Caracteristicas del Dataset_2:

person_age:	Age /
person_income:	Annual Income /
person_home_ownership:	Home ownership /
person_emp_length:	Employment length (in years) /
loan_intent:	Loan intent /
loan_grade;	Loan grade /
loan_amnt;	Loan amount /
loan_int_rate:	Interest rate /
loan_status:	Loan status (0 is non default 1 is default) /
loan_percent_income:	Percent income /
cb_person_default_on_file:	Historical default /
cb_preson_cred_hist_length:	Credit history length

**Dataset_3**

In [ ]:
url_ds_3 = 'https://raw.githubusercontent.com/mflazaro/bases_ds_python/main/german.csv'

df_st_3 = pd.read_csv(url_ds_3, sep=';')

df_st_3

,Creditability,Account_Balance,Duration_of_Credit_monthly,Payment_Status_of_Previous_Credit,Purpose,Credit_Amount,Value_Savings_Stocks,Length_of_current_employment,Instalment_per_cent,Sex_Marital_Status,...,Duration_in_Current_address,Most_valuable_available_asset,Age_years,Concurrent_Credits,Type_of_apartment,No_of_Credits_at_this_Bank,Occupation,No_of_dependents,Telephone,Foreign_Worker
0,1,1,18,4,2,1049,1,2,4,2,...,4,2,21,3,1,1,3,1,1,1
1,1,1,9,4,0,2799,1,3,2,3,...,2,1,36,3,1,2,3,2,1,1
2,1,2,12,2,9,841,2,4,2,2,...,4,1,23,3,1,1,2,1,1,1
3,1,1,12,4,0,2122,1,3,3,3,...,2,1,39,3,1,2,2,2,1,2
4,1,1,12,4,0,2171,1,3,4,3,...,4,2,38,1,2,2,2,1,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,0,1,24,2,3,1987,1,3,2,3,...,4,1,21,3,1,1,2,2,1,1
996,0,1,24,2,0,2303,1,5,4,3,...,1,1,45,3,2,1,3,1,1,1
997,0,4,21,4,0,12680,5,5,4,3,...,4,4,30,3,3,1,4,1,2,1
998,0,2,12,2,3,6468,5,1,2,3,...,1,4,52,3,2,1,4,1,2,1
999,0,1,30,2,2,6350,5,5,4,3,...,4,2,31,3,2,1,3,1,1,1

Caracteristicas del Dataset_3:

Account Balance: No account (1), None (No balance) (2), Some Balance (3) /
Payment Status: Some Problems (1), Paid Up (2), No Problems (in this bank) (3) /
Savings/Stock Value: None, Below 100 DM, [100, 1000] DM, Above 1000 DM /
Employment Length: Below 1 year (including unemployed), [1, 4), [4, 7), Above 7 /
Sex/Marital Status: Male Divorced/Single, Male Married/Widowed, Female /
No of Credits at this bank: 1, More than 1 /
Guarantor: None, Yes /
Concurrent Credits: Other Banks or Dept Stores, None /
ForeignWorker variable may be dropped from the study /
Purpose of Credit: New car, Used car, Home Related, Other

**Dataset_4**

In [ ]:
url_ds_4 = 'https://raw.githubusercontent.com/mflazaro/bases_ds_python/main/a_Dataset_CreditScoring.csv'

df_st_4 = pd.read_csv(url_ds_4, sep=';')

df_st_4

,TARGET,ID,DerogCnt,CollectCnt,BanruptcyInd,InqCnt06,InqTimeLast,InqFinanceCnt24,TLTimeFirst,TLTimeLast,...,TL50UtilCnt,TLBalHCPct,TLSatPct,TLDel3060Cnt24,TLDel90Cnt24,TLDel60CntAll,TLOpenPct,TLBadDerogCnt,TLDel60Cnt24,TLOpen24Pct
0,1,582,3,3,0,4,0.0,5,117,27,...,3.0,92%,21%,2,3,7,21%,4,4,0%
1,1,662,15,9,0,3,1.0,3,14,14,...,1.0,80%,0%,0,0,0,100%,12,0,100%
2,1,805,0,0,0,1,5.0,1,354,7,...,5.0,36%,65%,0,1,1,73%,1,1,53%
3,1,1175,8,5,0,6,1.0,10,16,4,...,3.0,91%,25%,1,1,1,75%,7,1,133%
4,1,1373,3,1,0,9,0.0,8,130,52,...,1.0,125%,0%,0,1,4,14%,3,1,0%
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,0,126441,0,0,0,2,0.0,2,199,10,...,9.0,79%,69%,0,0,0,65%,0,0,35%
2996,0,126448,0,0,0,0,NaN,0,270,3,...,5.0,58%,93%,0,0,0,86%,0,0,42%
2997,0,126465,1,1,0,8,0.0,5,234,4,...,9.0,87%,61%,0,0,0,43%,1,0,75%
2998,0,126487,4,4,0,2,3.0,1,257,3,...,3.0,104%,60%,0,1,2,60%,4,1,100%
2999,0,126503,2,1,1,0,18.0,0,254,119,...,1.0,32%,17%,0,2,4,50%,3,2,0%

Caracteristicas Dataset_4:

TARGET: Target variable, where 0 indicates good credit and 1 indicates bad credit. /
ID: Customer ID or unique identifier. /
DerogCnt: Number of derogatory remarks on the customer's credit report. /
CollectCnt: Number of collections on the customer's credit report. /
BanruptcyInd: Indicates whether the customer has declared bankruptcy (0 for no, 1 for yes). /
InqCnt06: Number of credit inquiries made by the customer in the last 6 months. /
InqTimeLast: Time (in months) since the last credit inquiry. /
InqFinanceCnt24: Number of credit inquiries related to financing in the last 24 months. /
TLTimeFirst: Time (in months) since the first credit line was opened. /
TLTimeLast: Time (in months) since the last credit line was opened. /
TLBalHCPct: Percentage of total credit line balance to high credit/limit. /
TLSatPct: Percentage of accounts where the customer's credit balance is close to the credit limit. /
TLDel3060Cnt24: Number of accounts with late payments (30-60 days) in the last 24 months. /
TLDel90Cnt24: Number of accounts with late payments (90+ days) in the last 24 months. /
TLDel60CntAll: Total number of accounts with late payments (60+ days). /
TLOpenPct: Percentage of open accounts. /
TLBadDerogCnt: Number of accounts with bad derogatory remarks. /
TLDel60Cnt24: Number of accounts with late payments (60+ days) in the last 24 months. /
TLOpen24Pct: Percentage of open accounts in the last 24 months.